language: android
jdk: oraclejdk7
android:
  components:
    - build-tools-19.1.0
    - android-19
    - sys-img-armeabi-v7a-android-19

env:
  matrix:
    - ANDROID_SDKS=android-19,sysimg-19 ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a
before_install:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - cp src/de/danoeh/antennapod/util/flattr/FlattrConfig.java.example src/de/danoeh/antennapod/util/flattr/FlattrConfig.java

before_script:
    - chmod -R 777 ./ci/wait_for_emulator.sh
    - ./ci/wait_for_emulator.sh

script:
    - gradle connectedAndroidTest
